- name: app setup      # descriptive name of the playbook task
  ansible.builtin.import_role:    # this part tells Ansible to import a role called 'common'  and run tasks defined in 'app-setup.yaml'
    name: common
    tasks_from: app-setup.yaml

- name: app setup      
  ansible.builtin.import_role:  
    name: common
    tasks_from: java.yaml

- name: app setup      # descriptive name of the playbook task
  ansible.builtin.import_role:    # this part tells Ansible to import a role called 'common'  and run tasks defined in 'app-setup.yaml'
    name: common
    tasks_from: system-setup.yaml

- name: import shipping data into mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml