- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-03c66e7a90fbbb324"
    zone_id: "Z05097823TWRPZG8NY41Q"
    domain_name: "dops.fun"
    # we can pass instances via command line also using -e option
    # instances:
    #   - mongodb
    #   - redis
    #   - mysql
    #   - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"  
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].public_ip_address }}" 
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      hosted_zone_id: "{{ zone_id }}"
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  - name: print the ec2_output.results
    ansible.builtin.debug:
      msg: "{{ ec2_output.results }}"
   